In [10]:
import numpy as np
matrix = np.arange(1, 31).reshape(6, 5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [12]:
matrix_2 = matrix[2:4, 0:2]
print(matrix_2)

[[11 12]
 [16 17]]


In [24]:
masked_matrix = np.zeros((6, 5))
masked_matrix[0, 1] = 2
masked_matrix[1, 2] = 8
masked_matrix[2, 3] = 14
masked_matrix[3, 4] = 20
print(masked_matrix)

[[ 0.  2.  0.  0.  0.]
 [ 0.  0.  8.  0.  0.]
 [ 0.  0.  0. 14.  0.]
 [ 0.  0.  0.  0. 20.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [26]:
masked_matrix_3 = np.zeros((6, 5))
masked_matrix_3[0, 3:] = [4, 5]  
masked_matrix_3[4, 3:] = [24, 25] 
masked_matrix_3[5, 3:] = [29, 30]
print(masked_matrix_3)

[[ 0.  0.  0.  4.  5.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 24. 25.]
 [ 0.  0.  0. 29. 30.]]
